In [35]:
import pandas as pd

In [36]:
df = pd.read_csv('E:/GitProjects/pandas/data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('E:/GitProjects/pandas/data/survey_results_schema.csv', index_col='Column')

In [37]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [38]:
df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [39]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8     116000.0
9          NaN
10     32315.0
11     40070.0
12     14268.0
13     38916.0
14     66000.0
15         NaN
Name: ConvertedComp, dtype: float64

In [40]:
df['ConvertedComp'].median()

54049.0

### 中位数

In [41]:
df.median()

Age                 29.0
CompTotal        63000.0
ConvertedComp    54049.0
WorkWeekHrs         40.0
dtype: float64

In [42]:
df.describe()

                Age      CompTotal  ConvertedComp   WorkWeekHrs
count  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean      30.834111  3.190464e+242   1.037561e+05     40.782174
std        9.585392            inf   2.268853e+05     17.816383
min        1.000000   0.000000e+00   0.000000e+00      1.000000
25%       24.000000   2.000000e+04   2.464800e+04     40.000000
50%       29.000000   6.300000e+04   5.404900e+04     40.000000
75%       35.000000   1.250000e+05   9.500000e+04     44.000000
max      279.000000  1.111111e+247   2.000000e+06    475.000000

In [43]:
df['ConvertedComp'].count()

34756

In [44]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4        Yes
5        Yes
        ...
64858    Yes
64867    Yes
64898    Yes
64925    Yes
65112    Yes
Name: Hobbyist, Length: 64461, dtype: object

### value_counts()可以查看各类型数据的数量

In [45]:
df['Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [46]:
df['SocialMedia']

KeyError: 'SocialMedia'

In [47]:
schema_df.loc['SocialMedia']

KeyError: 'SocialMedia'

In [48]:
df['SocialMedia'].value_counts()

KeyError: 'SocialMedia'

In [49]:
df['SocialMedia'].value_counts(normalize=True)

KeyError: 'SocialMedia'

In [50]:
df['Country'].value_counts()

United States                         12469
India                                  8403
United Kingdom                         3896
Germany                                3890
Canada                                 2191
                                      ...
Marshall Islands                          1
North Korea                               1
Nauru                                     1
Saint Lucia                               1
Micronesia, Federated States of...        1
Name: Country, Length: 183, dtype: int64

In [51]:
country_grp = df.groupby(['Country'])

In [52]:
country_grp.get_group('India')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"I’m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,NaN,NaN,"Developer, full-stack;Engineer, data","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,Slightly dissatisfied,I am actively looking for a job,Java;JavaScript;Python,Java;Python,NaN,NaN,NaN,NaN,Not sure,NaN,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,Every few months,No,Yes,No,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Windows,500 to 999 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,INR,Microsoft SQL Server,Microsoft SQL Server,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",South Asian,NaN,Family friendliness,Very satisfied,I am not interested in new job opportunities,C#;JavaScript;SQL;TypeScript,C#;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Stack Overflow for Teams,Stack Overflow for Teams,Yes,Extremely important,Very important,NaN,NaN,Once every few years,NaN,Yes,No,Often: 1-2 days per week or more,Ask developers I know/work with,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",NaN,Multiple times per day,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,DynamoDB,Firebase;MongoDB;MySQL,"Designer;Developer, back-end;Developer, front-...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",South Asian,Man,Flex time or a flexible schedule;How widely us...,NaN,I am actively looking for a job,Go;Kotlin;TypeScript,C;C++;HTML/CSS;Java;JavaScript;Python,Flutter;Node.js;React Native;TensorFlow,NaN,Confluence;Stack Overflow for Teams,Github;Facebook Workplace;Slack;Microsoft Team...,NaN,NaN,NaN,NaN,NaN,Once a year,Yes,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,NaN,AWS;Docker;Heroku;iOS,Android;Arduino;Google Cloud Platform;Raspberr...,NaN,Straight / Heterosexual,Yes,Neutral,A few times per week,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,INR,Cassandra;MySQL;PostgreSQL,MySQL;PostgreSQL,"Developer, back-end;Developer, QA or test;DevO...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,East Asian,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C;C++;Java;Perl;Scala,Bash/Shell/PowerShell;C++;Perl,Apache Spark,NaN,Confluence;Jira;Github;Gitlab;Google Suite (Do...,"Confluence;Jira;Github;Google Suite (Docs, Mee...",Not sure,Neutral,Critically important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Indifferent,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Linux-based,500 to 999 employees,Google Cloud Platform;Linux,Linux,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,NaN,MongoDB;MySQL,MySQL,"Developer, full-stack;Developer, QA or test","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL,C;HTML/CSS;Java;JavaScript;PHP;Python;SQL,NaN,NaN,Jira;Github;Gitlab;Slack,Jira;Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Linux-based,NaN,Linux;Windows,Linux;Windows,NaN,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Associate degree (A.A., A.S., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
filt = df['Country'] == 'India'
df.loc[filt]['SocialMedia'].value_counts()

KeyError: 'SocialMedia'

In [54]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['China']

KeyError: 'Column not found: SocialMedia'

In [55]:
country_grp['ConvertedComp'].median().loc['Germany']

62697.0

In [56]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68068.000000
mean      115101.775465
Name: Canada, dtype: float64

In [57]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

2670

In [69]:
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'loc'

In [59]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              11
Albania                                  13
Algeria                                  40
Andorra                                   3
Angola                                    1
                                       ...
Venezuela, Bolivarian Republic of...     29
Viet Nam                                102
Yemen                                     1
Zambia                                    4
Zimbabwe                                 13
Name: LanguageWorkedWith, Length: 183, dtype: int64

In [60]:
country_respondents = df['Country'].value_counts()
country_respondents

United States                         12469
India                                  8403
United Kingdom                         3896
Germany                                3890
Canada                                 2191
                                      ...
Marshall Islands                          1
North Korea                               1
Nauru                                     1
Saint Lucia                               1
Micronesia, Federated States of...        1
Name: Country, Length: 183, dtype: int64

In [61]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              11
Albania                                  13
Algeria                                  40
Andorra                                   3
Angola                                    1
                                       ...
Venezuela, Bolivarian Republic of...     29
Viet Nam                                102
Yemen                                     1
Zambia                                    4
Zimbabwe                                 13
Name: LanguageWorkedWith, Length: 183, dtype: int64

### 连接两列

In [70]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                                    Country  LanguageWorkedWith
United States                         12469                5964
India                                  8403                2670
United Kingdom                         3896                1621
Germany                                3890                1712
Canada                                 2191                1011
...                                     ...                 ...
Marshall Islands                          1                   0
North Korea                               1                   0
Nauru                                     1                   0
Saint Lucia                               1                   1
Micronesia, Federated States of...        1                   1

[183 rows x 2 columns]

In [63]:
python_df.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [64]:
python_df

                                    NumRespondents  NumKnowsPython
United States                                12469            5964
India                                         8403            2670
United Kingdom                                3896            1621
Germany                                       3890            1712
Canada                                        2191            1011
...                                            ...             ...
Marshall Islands                                 1               0
North Korea                                      1               0
Nauru                                            1               0
Saint Lucia                                      1               1
Micronesia, Federated States of...               1               1

[183 rows x 2 columns]

In [65]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython']/python_df['NumRespondents']) * 100
python_df

,NumRespondents,NumKnowsPython,PctKnowsPython
United States,12469,5964,47.830620
India,8403,2670,31.774366
United Kingdom,3896,1621,41.606776
Germany,3890,1712,44.010283
Canada,2191,1011,46.143314
...,...,...,...
Marshall Islands,1,0,0.000000
North Korea,1,0,0.000000
Nauru,1,0,0.000000
Saint Lucia,1,1,100.000000
"Micronesia, Federated States of...",1,1,100.000000

In [66]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [67]:
python_df.head(50)

,NumRespondents,NumKnowsPython,PctKnowsPython
"Micronesia, Federated States of...",1,1,100.000000
Saint Lucia,1,1,100.000000
Gabon,1,1,100.000000
Montenegro,13,9,69.230769
Brunei Darussalam,3,2,66.666667
Guyana,5,3,60.000000
Swaziland,7,4,57.142857
Iceland,53,28,52.830189
Finland,349,183,52.435530
Uganda,81,42,51.851852
Mauritania,4,2,50.000000
Burkina Faso,6,3,50.000000
Papua New Guinea,2,1,50.000000
Timor-Leste,2,1,50.000000
Jamaica,14,7,50.000000
Solomon Islands,2,1,50.000000
Belize,4,2,50.000000
Cameroon,50,24,48.000000
United States,12469,5964,47.830620
Israel,653,307,47.013783
Ecuador,49,23,46.938776
Taiwan,158,73,46.202532
Canada,2191,1011,46.143314
Oman,11,5,45.454545
Estonia,145,65,44.827586
Ireland,444,199,44.819820
Japan,297,132,44.444444
Switzerland,629,278,44.197138
Germany,3890,1712,44.010283
France,1898,833,43.888303
Singapore,228,99,43.421053
Costa Rica,76,33,43.421053
Australia,1208,524,43.377483
Democratic Republic of the Congo,7,3,42.857143
Trinidad and Tobago,7,3,42.857143
Lao People's Democratic Republic,7,3,42.857143
China,371,158,42.587601
Peru,101,43,42.574257
Algeria,94,40,42.553191
Malta,47,20,42.553191
Zimbabwe,31,13,41.935484
Norway,384,160,41.666667
New Zealand,353,147,41.643059
United Kingdom,3896,1621,41.606776
Hong Kong (S.A.R.),111,46,41.441441
"Venezuela, Bolivarian Republic of...",70,29,41.428571
Slovenia,157,65,41.401274
Kenya,271,111,40.959410
Netherlands,1343,544,40.506329
Qatar,20,8,40.000000

In [68]:
python_df.loc['Japan']

NumRespondents    297.000000
NumKnowsPython    132.000000
PctKnowsPython     44.444444
Name: Japan, dtype: float64